// AUTO-GENERATED by configure_xcode.rb - DO NOT EDIT MANUALLY
// This file is regenerated on each test run with discovered test files

#import "AppDelegate.h"
#import <unistd.h>

extern int test_engine_main();
extern int test_graph_main();
extern int test_index_main();
extern int test_kernel_main();
extern int test_kv_cache_main();
extern int test_performance_main();

@implementation AppDelegate

- (void)copyFromBundle:(NSString *)bundlePath toDocuments:(const char *)name {
    if (!name) return;
    NSFileManager *fileManager = [NSFileManager defaultManager];
    NSString *itemName = [NSString stringWithUTF8String:name];
    NSString *sourceItemPath = [NSString stringWithFormat:@"%@/%@", bundlePath, itemName];
    if ([fileManager fileExistsAtPath:itemName]) {
        [fileManager removeItemAtPath:itemName error:nil];
    }
    [fileManager copyItemAtPath:sourceItemPath toPath:itemName error:nil];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = paths[0];
    chdir([documentsDirectory UTF8String]);

#if !TARGET_OS_SIMULATOR
    freopen("cactus_test.log", "w", stdout);
    freopen("cactus_test.log", "a", stderr);
    setbuf(stdout, NULL);
    setbuf(stderr, NULL);
#endif

    NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_MODEL")];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_TRANSCRIBE_MODEL")];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_ASSETS")];

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        test_engine_main();
        test_graph_main();
        test_index_main();
        test_kernel_main();
        test_kv_cache_main();
        test_performance_main();
        exit(0);
    });

    return YES;
}

@end
